version: "1.0.{build}"
image: Visual Studio 2022

environment:
  NugetApiKey:
    secure: 6VwMB2mqQSx7mbr3n1eimI13FgAzGrWqAOEi/JO2cK2d3F56Ki1e5Suc6nsSpE2U

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"

pull_requests:
  do_not_increment_build_number: true

# branches:
#   only:
#     - master
#     - develop
#     - /feature\/.*/

nuget:
  disable_publish_on_pr: false

test: off

build_script:
  - ps: ./build.ps1

  after_build:
- ps: >-
    $branch = $ENV:APPVEYOR_REPO_BRANCH;
    $fileVersion = $env:APPVEYOR_BUILD_VERSION;
    if($branch -ne 'master') {
        $fileVersion = "${fileVersion}-${branch}"; 
    }
    
    $fileVersion = $fileVersion.replace("release/", "");
    $fileVersion = $fileVersion.replace("feature/", "");
    $fileVersion = $fileVersion.replace("bugfix/", "");
    dotnet pack templates -o ((get-location).Path + '\artifacts') --no-build /property:Version=$fileVersion 
    
artifacts:
- path: artifacts\**\*.*

deploy_script:
  - ps: dotnet nuget push .\artifacts\*.nupkg -k $env:NugetApiKey --source https://api.nuget.org/v3/index.json
