version: '1.0.{build}'
image: Visual Studio 2019
environment:
  NugetApiKey:
    secure: NK6JEky2i7+06Ij+PlJX7X0xlKT4fg2zDIFP5fiFSy6EqxcIYThFBkzzqpQTUnsO
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
test: off
build_script:
  - dotnet restore .\templates
  - dotnet pack .\templates\templates.csproj -o .\ --no-build
deploy_script:
  - ps: dotnet nuget push "*.nupkg" -k $env:NugetApiKey
 