version: "1.0.{build}"
image: Visual Studio 2022

environment:
  NugetApiKey:
    secure: D7B7/pzGIeteV3H4DrdBtyKCxLrgcBAL6XWtWrm/kJrshDwUZ5acauR9QWll7TWi

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - develop
#  - /feature\/.*/

nuget:
  disable_publish_on_pr: true

test: off

build_script:
  - ps: ./build.ps1

artifacts:
  - path: artifacts\**\*.*

deploy_script:
  - ps: dotnet nuget push .\artifacts\*.nupkg -k $env:NugetApiKey --source https://api.nuget.org/v3/index.json
