version: '1.0.{build}'
image: Visual Studio 2022

environment:
  NugetApiKey:
    secure: NK6JEky2i7+06Ij+PlJX7X0xlKT4fg2zDIFP5fiFSy6EqxcIYThFBkzzqpQTUnsO
    
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  
pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - develop

nuget:
  disable_publish_on_pr: true

test: off

build_script:
- ps: ./build.ps1
  
deploy_script:
  - ps: dotnet nuget push .\artifacts\*.nupkg -k $env:NugetApiKey --source https://api.nuget.org/v3/index.json
 